version: '3.8'

services:
  python-kafka-tensorflow:
    image: python:3.8-slim
    restart: always
    command: tail -f /dev/null
    volumes:
      - sit_light_controller:/data  
    tty: true  
    container_name: sit-light-controller-container
    environment:
      - TZ=America/Detroit
      - RELEASE_VERSION=${RELEASE_VERSION}
      - BRIDGE_IP=${BRIDGE_IP}
      - USER_TOKEN=${USER_TOKEN}
      - BROKER=${BROKER}
      - LIGHT_ID=${LIGHT_ID}
      - LIGHT_OFF_CONFIG=${LIGHT_OFF_CONFIG}
      - LIGHT_ON_CONFIG=${LIGHT_ON_CONFIG}

    networks:
      - alpine-net
    entrypoint: |
      /bin/bash -c "
      apt-get update && apt-get install -y --no-install-recommends git curl python3-venv;
      python3 -m venv /venv;
      source /venv/bin/activate;
      pip install --no-cache-dir pytz kafka-python python-dotenv requests;

      if [ ! -d /data/sit-light-controller-v${RELEASE_VERSION} ]; then
        mkdir -p /data/sit-light-controller-v${RELEASE_VERSION} && \
        curl -L https://github.com/DevinMB/sit-light-controller/archive/refs/tags/v${RELEASE_VERSION}.tar.gz | tar xz --strip-components=1 -C /data/sit-light-controller-v${RELEASE_VERSION};
      fi
      
      python3 /data/sit-light-controller-v${RELEASE_VERSION}/sit_light_controller.py;
      "

networks:
  alpine-net:
    driver: bridge

volumes:
  sit_light_controller:  
